### ISSUE TITLE
AppRegistryNotReady: Apps aren't loaded yet.

### ISSUE THREAD

**Issue by pydevd** [pydanny/dj-spam#11]
Trying to use this package in my project. I'm done everything as in the manual, but I'm getting this error:
`
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.`

Stack trace:

<pre>Traceback (most recent call last):
  File "/usr/lib/pycharm/helpers/pydev/_pydev_bundle/pydev_monkey.py", line 553, in __call__
    return self.original_func(*self.args, **self.kwargs)
  File "/home/joker/projects/coastskills/env/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/joker/projects/coastskills/env/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/joker/projects/coastskills/env/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/joker/projects/coastskills/env/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/joker/projects/coastskills/env/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/joker/projects/coastskills/env/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/joker/projects/coastskills/env/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/lib/python2.7.11/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/joker/projects/coastskills/env/lib/python2.7/site-packages/spam/__init__.py", line 4, in <module>
    from .behaviors import Spammable
  File "/home/joker/projects/coastskills/env/lib/python2.7/site-packages/spam/behaviors.py", line 4, in <module>
    class Spammable(models.Model):
  File "/home/joker/projects/coastskills/env/lib/python2.7/site-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/joker/projects/coastskills/env/lib/python2.7/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/home/joker/projects/coastskills/env/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.</pre>

I'm using Django 1.9.6, what I'm doing wrong?

**Comment by pydanny** [comment]
The software is pre-alpha (https://github.com/pydanny/dj-spam/blob/master/setup.py#L48) and hasn't been touched since before 1.9 was released.

**Comment by pydanny** [comment]
Apologies, that was a bit terse. The problem is that I started this project but haven't had a chance to maintain our polish it.
